language: ruby
rvm:
- 2.6.3
services:
- postgresql
before_install:
- gem update --system
- gem install bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
script:
- bundle exec rspec
after_script:
- bundle exec rake coveralls:push
deploy:
  provider: heroku
  api_key:
    secure: F7NneJm0wwFyKDvpnzAK3TPS+/7Fbndpj4aRmAURx3HEWbcFZVFVT9CJDjnGSUI865MbrdDuCWcBhO9R2HjCQdJzJMN5CLWbq2T0qsI1aD8yVx560lZqKY4Q2O6QsVSHLVfMPxQhkgy84NqAt1lnPQIrXZ8/exysIj3lPRfnO3CgUuLg0uh1ffviGYHHGiMGZpz4U+Tv8Esnn3D1Q+uE8i3umAN1yyZEbh/7dsQ/KljJVXTyHquEfXsS/2qMUuKpTCHCATlUkcuDkbSORKE7aHXka0uwuh9XcXwXyUgVYhTpUicFvGen/3WbRR7ykvNwfD3pk2LT433v4/CNHNX0wVvjHyHV1tzXVRSNknN2y76eq2Le4ovg3+geRkcqRPXFMfx/HwDPKnL5y16xK5LSIJI04beZ0EhkXC5w4dOSSaYwX1TtCafr7xxjVwEvUKeHA+Ffm90F60w5ZwhP/piA8AqA2jogmNX+OkVL/N9nEBtywVDhTgRmgmp95zW+SV+0VzWUI8/VW2oOHLg9QjMO5G8P74HCniKtY2CYqh3ESTS4fM3ZfyF4PmG5k5cA/8zZuLCEq8RonFlpTo2wJACgGBQ1aHFbWYzL3cg2EW726pWwbka97qYw54IWWdmjv/avYBwmDCK6dPdHx8SbtkWCowBDfZNSjCkGF0+qerw0rGI=
  app: rails-test-app-article
  on:
    repo: hughbric/translator_server
env:
  global:
    secure: KeB8QZmmze4siyBWXN4hJMBAilNtAfWSU/OZYpOg2Gj5vQigToMszBPuBD8dag+AUduaQvguQKb5COx0Ss/k7TEj968Qy+Q+x9ia5mp/WNM5h2TqDgz0pbFSfQp9nmnOglo3pIR7+u7EB5FD/2ljSzBUXAc0BtcxnRkVB7n3nby/6RSCoFHenwCW0eqXtGXqlfCf+KUOZjZ+ABSenxYD6R6UKisNK9CCWnZb45BUlUQ+SBHM38EuhDFZsKTGLW0ZbGbPY3Q5gOWWhgLKfV87LWKxpnlj5GAutIY7O5dqV6zhJ1G2WjDAx9C1xHIy5S6CN9xeu14BVKAcYQ60KFxodRtD0N0YOQnaSTY52buISB27V96SV7Ro+3FhpdXsfG63qwLrQ+9wMFCUwS3QOSogUBjOMqHNwWFodsT8KyUQDb38sraHQfa5+6Vn8x1Ry5QzLsWVwCy64oLLHHvSvaDAUrv4NyLaWhfsbjb64nC+5ERqN+6IeocDJ4cgn/V1gHOb7w4V7K6yyR6TUH6I2jumrcQQWQMYzuDzSsd8sinin2sYTHTSHjK6q7KulTXzJ32GIWtXUtwN+uXhvuXHGKa1pwBwpWaMdE8i57f4yHMBJGvCm/zBFYYCUKzC4Kxlm6VCaO0QcKHDx//M0tzfK8guJ4HaEJaJsLh2yyJdi7MQyy0=
